name: Sync Etsy to Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # cada día a las 07:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
      ETSY_PROFILE_URL: ${{ secrets.ETSY_PROFILE_URL }}
      SHEET_TAB: etsy_items   # nombre de pestaña (no es secret)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread google-auth
          playwright install --with-deps chromium

      - name: Run sync
        run: |
          python sync_etsy_to_sheets.py
