name: Sync Wallapop to Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # cada día a las 07:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread oauth2client
          playwright install --with-deps chromium

      - name: Run sync
        env:
          WALLAPOP_PROFILE_URL: ${{ secrets.WALLAPOP_PROFILE_URL }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_TAB: ${{ secrets.SHEET_TAB }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_JSON }}
        run: |
          python sync_wallapop_to_sheets.py
