name: Sync Vinted to Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # cada día a las 07:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
      VINTED_PROFILE_URL: ${{ secrets.VINTED_PROFILE_URL }}
      SHEET_TAB: vinted_items   # no es secret; nombre fijo de la pestaña

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread google-auth
          playwright install --with-deps chromium

      - name: Run sync
        run: |
          python sync_vinted_to_sheets.py
