name: Sync Vinted → Google Sheets

on:
  workflow_dispatch:       # Permite lanzarlo manualmente
  schedule:
    - cron: "*/15 * * * *"   # Cada 15 minutos

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          VINTED_USER_ID: ${{ secrets.VINTED_USER_ID }}
          VINTED_DOMAIN: ${{ secrets.VINTED_DOMAIN }}
        run: python sync_vinted_to_sheets.py
