name: Sync Etsy → Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: "17 6 * * *"  # diario 06:17 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth requests

      - name: Run sync
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
          SHEET_TAB_ETSY: ${{ secrets.SHEET_TAB_ETSY }}  # opcional
          ETSY_PROFILE_URL: ${{ secrets.ETSY_PROFILE_URL }}  # o ETSY_SHOP_NAME/ETSY_SHOP_ID
          ETSY_SHOP_NAME: ${{ secrets.ETSY_SHOP_NAME }}
          ETSY_SHOP_ID: ${{ secrets.ETSY_SHOP_ID }}
          ETSY_CLIENT_ID: ${{ secrets.ETSY_CLIENT_ID }}      # keystring
          ETSY_REFRESH_TOKEN: ${{ secrets.ETSY_REFRESH_TOKEN }}
        run: |
          python sync_etsy_to_sheets.py
